spring:
  datasource:
    url: jdbc:h2:mem:testdb   # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true           # Enable H2 web console
      path: /h2-console       # Access via http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update        # Options: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
